name: Default action

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: docker build . --file Dockerfile --tag phox-pro/nebula-atom:$(date +%s)

      - name: Run tests
        run: ./vendor/bin/phpunit
