name: Default action

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy compose file
        run: cp docker-compose.yml docker-compose.test.yml

      - name: Build container
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Run tests
        run: ./vendor/bin/phpunit
